version: '3.9'

services:
  app:
    build: .
    image: api-node:latest
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: notas_db
      DB_PORT: 5432
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notas_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    name: app-network
    driver: bridge
